### ISSUE TITLE
How could I get the real distance from the depthmap output?

### ISSUE THREAD

**Issue by HarderThenHarder** [ialhashim/DenseDepth#117]
Hello, could you tell me how can I get the real distance (ex: 1.23m) of each pixel according to the depthmap output (ex: 0.132)?

**Comment by ialhashim** [comment]
If the outputs are in the range from 0 to 1, then you need to scale it back to the training range (for NYU its 0 to 10 meters). So you just need to multiply by 10.

**Comment by hirosue** [comment]
Thank you for your amazing work. I'm sorry but I'm a bit confused when I read your paper. In section "3.2. Learning and Inference", you write "y = m/y_orig". Should it be "y = y_orig/m"? Thanks!

**Comment by binwang777** [comment]
> 
> 
> Thank you for your amazing work. I'm sorry but I'm a bit confused when I read your paper. In section "3.2. Learning and Inference", you write "y = m/y_orig". Should it be "y = y_orig/m"? Thanks!

When you get NYU output from the model, you need some additional processing. In simple terms, it is to find a countdown. (From y = m / y_orig ---> y = y_orig / m), then if you need the real distance, then multiply by 10, which is m = 10. Of course, for accuracy, you can also use accurate scalar instead of 10.
