### ISSUE TITLE
problem with glm

### ISSUE THREAD

**Issue by abdur4373** [ialhashim/DenseDepth#29]
Hello @ialhashim @cclauss  Hope you are doing well, I must appreciate good work done by you.
I am implementing your work in py charm and getting error
AttributeError: module 'glm' has no attribute 'vec3'
All the code with glm. is giving error, I am not sure what is the reason because I have installed glm with pip version 0.3.4.
Could you help me with this, 
Thanks in advance.....

**Comment by cclauss** [comment]
https://pypi.org/project/PyGLM vs. https://pypi.org/project/glm ??

**Comment by ialhashim** [comment]
@abdur4373 this is only needed for the demo (sorry for the messy code there). I believe you need the packages `PyGLM PySide2`.

@cclauss I found it tricky to create such a cross-platform requirements file mainly due to TensorFlow. So far the best strategy to train the models on a new Linux or Windows machine is to create an environment like so `conda create --name tf_gpu tensorflow-gpu` then install the packages `pip install keras pillow matplotlib scikit-learn scikit-image opencv-python pydot graphviz`. Trying to extract a requirements file or environment file never seem to work for me in a cross-platform manner out of the box.

**Comment by cclauss** [comment]
In __requirements.txt__ you can use [environment markers](https://pip.pypa.io/en/stable/reference/pip_install/#requirement-specifiers) to conditionally install on various platforms.

**Comment by masterchop** [comment]
i dont understand what is the solution if i uninstall glm it asks for it???

**Comment by kwccoin** [comment]
Strangely after install all those in the requirement, I need to uninstall glm!!! (Based on a Korean site ... cannot read Korean but can guess.)

```
pip3 uninstall gem
```

based on requirement txt of one 3D YouTube sample
```
moderngl
numpy
pygame
PyGLM
pywavefront
```

**Comment by rigvedepur** [comment]
pip3 uninstall glm worked
