### ISSUE TITLE
How to  get the real world distance value from the camera to the object by using depth map image 

### ISSUE THREAD

**Issue by vigneshgig** [ialhashim/DenseDepth#38]
Hi , I want to know how to calculate the real world distance value from the camera to object. And I am using my own image so which mean pretrained model trained on different camera config. So how can I calibrate this pretrained model to my own camera input image. 
Thanks for advance

**Comment by ialhashim** [comment]
The models are trained to output `maxDepth/x` values so we just convert the raw output by again applying `maxDepth/x` giving us values in the range `[0,1]` where 0 is sensor distance and 1 is the maximum distance trained on (which 10 meters for NYU and 80 meters for KITTI). If you provide your own image from any source the network will regress something that is closest to the domain it trained on. It gets less accurate the more you change it from the typical Kinect setup (or KITTI capture setup).

This model trains in a supervised manner (you need corresponding pairs of RGB and Depth images). In order to fine-tune the trained model you would have to train the model some more on the new capture device. If you don't have access to that then there is unfortunately no straightforward way to do any calibration.

**Comment by shuluoshu** [comment]
> The models are trained to output `maxDepth/x` values so we just convert the raw output by again applying `maxDepth/x` giving us values in the range `[0,1]` where 0 is sensor distance and 1 is the maximum distance trained on
hi,  @ialhashim , 
I wonder if the real depth is 10cm to 1000cm, `maxDepth/x` is `1~100`, not 0-1,  so does the network output 1-100?  From what you said, I am confused.

**Comment by ialhashim** [comment]
The predict function is made to output from 0 to 1 that corresponded to real world distance from 1 to 10 meters in the case of NYU. You can take a look at the computation and try to understand what is going on (its in utils.py).

**Comment by shuluoshu** [comment]
> The predict function is made to output from 0 to 1 that corresponded to real world distance from 1 to 10 meters in the case of NYU. You can take a look at the computation and try to understand what is going on (its in utils.py).


Thanks for your quick reply. Do you mean the `predict` function here: 
```
predictions = model.predict(images, batch_size=batch_size)
return np.clip(DepthNorm(predictions, maxDepth=maxDepth), minDepth, maxDepth) / maxDepth
```
the returned res should be `(maxDepth / predictions) / maxDepth =  1/ predictions` then. 
  1/ predictions is  between 0-1, am I right?
