### ISSUE TITLE
About image size

### ISSUE THREAD

**Issue by Hackerlil** [ialhashim/DenseDepth#50]
have you test about smaller image size input?I wonder if a smaller size of input would make results worse?(for example if the input is 224x224,output is 112x112,)

**Comment by ialhashim** [comment]
It makes the testing results worse since the test set is defined as 640x480. Here is a figure comparing the performance (with the same amount of training) on the same test set with different input resolutions:

![image](https://user-images.githubusercontent.com/2434978/63268267-74191b80-c29c-11e9-924f-e7700963818c.png)
