### ISSUE TITLE
Prediction is multiplied by 10

### ISSUE THREAD

**Issue by slanidjani** [ialhashim/DenseDepth#7]
In the evaluate function of the utils module, you multiply your predictions with 10.0 after scaling the depth map. Why are you doing this? I can't find any information about this in the code or in the paper.

**Comment by ialhashim** [comment]
The predict function ends with the line:
https://github.com/ialhashim/DenseDepth/blob/b6f2a3ffc84f025397d180e7c50ecfcf6eebe0f0/utils.py#L14

So the range of the prediction is from [0,1]. We multiply by 10.0 in the evaluation to scale the values to the same range as the ground truth, where the maximum depth is 10 meters.

**Comment by slanidjani** [comment]
I see, thanks for the quick reply. Are the provided weights+model for the KITTI dataset trained on lidar data capped at 80 meters?

**Comment by ialhashim** [comment]
Yes they should be.

**Comment by gd2016229035** [comment]
why the maximun depth of ground truth is 10 meters, while it is actually 80 meters in dataset? I am confused about how to scale the prediction which is from [0,1] , or original values directly from network output to the real distance(meters)?

**Comment by ialhashim** [comment]
10 meter for NYU and 80 meter for KITTI.

**Comment by resindraburiza** [comment]
Hello, I want to ask a related thing. So, instead of opening new issue, I will ask it here.
I want to ask about a line of code in `NYU_BasicRGBSequence(Sequence)`
`y = np.asarray(Image.open(BytesIO(self.data[sample[1]])), dtype=np.float32).reshape(480,640,1).copy().astype(float) / 10.0`

so, the 10.0 here is the max depth in meters for NYU dataset to scale the result in range of [0 1]? Am I correct? Thank you again for your assistance.

Best,
Resindra

**Comment by ialhashim** [comment]
I believe this 10 is not for that purpose since all training data is in the range of 10 to 1000 (cm) (before `DepthNorm`). 

This divide by 10 is only because the test data was saved in a different range unfortunately (got it from another source online). Notice how in the regular data loader we multiply by `maxDepth` after dividing by 255: https://github.com/ialhashim/DenseDepth/blob/f376b01820cad7f57222c5a24e40e89577a2c269/data.py#L70

**Comment by resindraburiza** [comment]
Aha, I see. That makes sense since the depth map of the test data is not as contrast as the training data. So, they indeed have a different scale I suppose.

In that case, if I have my own data, I need to make sure that the range of depth map of (y) in both training/regular data loader and the test data loader are the same. Is it correct? Thank you again.

Best,
Resindra

**Comment by LP940708** [comment]
> 10 meter for NYU and 80 meter for KITTI.

Why the maximum depth for KITTI is 80 meters?
