### ISSUE TITLE
output depth shape different from input image

### ISSUE THREAD

**Issue by LiZhenLiangLee** [ialhashim/DenseDepth#96]
Hi
I run test.py , and I use the pretrained model of NYUD-v2. my input image is 480x640 , but the output shape is 240x320, why ?
I want to get the depth of each pixel, but the output shape is smaller than input.
looking forward to your reply.

**Comment by LiZhenLiangLee** [comment]
And  I use the pretrained model of NYUD-v2

**Comment by ialhashim** [comment]
That is expected. The encoder decoder in our architecture only up-sample to half the input resolution. You can either downsample your RGB or upsample the depth map after the estimation. The original reason has to do with GPU limitation and size of model.

**Comment by resindraburiza** [comment]
Hi @ialhashim ,

I am sorry for hijacking this closed issues because I have a question. So, other than GPU memory limitation, there is no other reason not to do one more upsampling in the decoder part? Do you think an additional upsample layer + its skip connection to achieve the same depth resolution will have any effect on model prediction accuracy?

Best,
resindra

**Comment by ialhashim** [comment]
I have tried that recently and there is no advantage in terms of performance that I can see.

**Comment by resindraburiza** [comment]
Hi, 

thank you very much for fast reply! Also thank you for your answer. It seems normal upsampling is enough then.

best,
resindra
