### ISSUE TITLE
Evaluation script gives different results on Pre-Trained model.

### ISSUE THREAD

**Issue by prass-anyvision** [ialhashim/DenseDepth#98]
Hey, I went through the evaluation script, and it seems to give different results on the supplied NYU-v2 test data, as compared to the table in the paper :- 

These are the evaluation metrics that I get :- 

```
        a1,         a2,         a3,        rel,        rms,     log_10
    0.8471,     0.9731,     0.9937,     0.1274,     0.5485,     0.0535
```

Why the difference?

**Comment by prass-anyvision** [comment]
@ialhashim  is this expected?

**Comment by prass-anyvision** [comment]
Also, why is there a factor of 10 that the models are multiplied by?

**Comment by ClarissaYL** [comment]
I found that in `utils.py`, the input order of function `compute_errors` should be reversed, so that can match its use in `evaluate`. And this will results in the only difference in rel=0.1234. Except from this, I got the exactly same results as you did. I'm confused too why rms is much larger compared to the paper.
